{
 "title": "UCloud UHost",
 "description": "Visualize UCloud UHost metrics",
 "tags": [
  "UCLoud",
  "UMon",
  "UHost"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "ucloud-monitor-datasource" },
   {
    "name": "projectId",
    "label": "ProjectId",
    "query": "{\"Action\": \"GetProjectId\" }"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "{\"Action\": \"GetRegion\", \"ProjectId\":\"$projectId\"}"
   },
   {
    "name": "resourceId",
    "label": "ResourceId",
    "query": "{\"Action\": \"GetResourceId\", \"ProjectId\":\"$projectId\", \"ResourceType\":\"uhost\", \"Region\":\"$region\" }"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization [max %]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "projectId": "$projectId",
     "region": "$region",
     "resourceType": "uhost",
     "metricName": "CPUUtilization",
     "resourceId": "$resourceId"
    }
   ]
  },
  {
   "title": "Network details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound network traffic [bytes/sec]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "projectId": "$projectId",
       "region": "$region",
       "resourceType": "uhost",
       "metricName": "NICIn",
       "resourceId": "$resourceId"
      }
     ]
    },
    {
     "title": "Outbound network traffic [bytes/sec]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "projectId": "$projectId",
       "region": "$region",
       "resourceType": "uhost",
       "metricName": "NICOut",
       "resourceId": "$resourceId"
      }
     ]
    },
    {
     "title": "Inbound network packets [NetPacketIn]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "projectId": "$projectId",
       "region": "$region",
       "resourceType": "uhost",
       "metricName": "NetPacketIn",
       "resourceId": "$resourceId"
      }
     ]
    },
    {
     "title": "Outbound network packets [NetPacketOut]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "projectId": "$projectId",
       "region": "$region",
       "resourceType": "uhost",
       "metricName": "NetPacketOut",
       "resourceId": "$resourceId"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "The following metrics are reported for UHost Instance Disk.",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
    },
    {
     "title": "Disk READ [bytes/sec]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "projectId": "$projectId",
       "region": "$region",
       "resourceType": "uhost",
       "metricName": "DiskReadOps",
       "resourceId": "$resourceId"
      }
     ]
    },
    {
     "title": "Disk WRITE [bytes/sec]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "projectId": "$projectId",
       "region": "$region",
       "resourceType": "uhost",
       "metricName": "DiskWriteOps",
       "resourceId": "$resourceId"
      }
     ]
    },
    {
     "title": "Disk READ [IORead]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "projectId": "$projectId",
       "region": "$region",
       "resourceType": "uhost",
       "metricName": "CPUUtilization",
       "resourceId": "$resourceId"
      }
     ]
    },
    {
     "title": "Disk WRITE [IOWrite]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "projectId": "$projectId",
       "region": "$region",
       "resourceType": "uhost",
       "metricName": "IOWrite",
       "resourceId": "$resourceId"
      }
     ]
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "content": "For more information about avaialble metrics from UCloud UHost, visit the [List of Available UCloudMonitor Metrics for Your UHost Instances](https://docs.ucloud.cn/api/umon-api/get_metric) in the UCLoud documentation.",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  }
 ]
}